// <auto-generated />
using System;
using CSDLGia_ASP.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSDLGia_ASP.Migrations
{
    [DbContext(typeof(CSDLGiaDBContext))]
    [Migration("20220311042441_tblHeThong")]
    partial class tblHeThong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSDLGia_ASP.Models.tblDMChucNang", b =>
                {
                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CapDo")
                        .HasColumnType("int");

                    b.Property<bool>("CongBo")
                        .HasColumnType("bit");

                    b.Property<bool?>("DM_DanhSach")
                        .HasColumnType("bit");

                    b.Property<bool?>("DM_ThayDoi")
                        .HasColumnType("bit");

                    b.Property<bool?>("HS_DanhSach")
                        .HasColumnType("bit");

                    b.Property<bool?>("HS_HoanThanh")
                        .HasColumnType("bit");

                    b.Property<bool?>("HS_ThayDoi")
                        .HasColumnType("bit");

                    b.Property<bool?>("K_BaoCao")
                        .HasColumnType("bit");

                    b.Property<bool?>("K_ThongTin")
                        .HasColumnType("bit");

                    b.Property<string>("KiHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TenBangChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBangHoSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("UrlTongHop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucNang");

                    b.ToTable("tblDMChucNang");
                });

            modelBuilder.Entity("CSDLGia_ASP.Models.tblDSDiaBan", b =>
                {
                    b.Property<string>("MaDiaBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDiaBan");

                    b.ToTable("tblDSDiaBan");
                });

            modelBuilder.Entity("CSDLGia_ASP.Models.tblDSDonVi", b =>
                {
                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVuKyThay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVuQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailQuanTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDiaBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQHNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayLamViec")
                        .HasColumnType("int");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViChuQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonVi");

                    b.ToTable("tblDSDonVi");
                });

            modelBuilder.Entity("CSDLGia_ASP.Models.tblDSTaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NhapLieu")
                        .HasColumnType("bit");

                    b.Property<bool?>("QuanTri")
                        .HasColumnType("bit");

                    b.Property<int?>("STT")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLanDangNhap")
                        .HasColumnType("int");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TongHop")
                        .HasColumnType("bit");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("TenDangNhap");

                    b.ToTable("tblDSTaiKhoan");
                });

            modelBuilder.Entity("CSDLGia_ASP.Models.tblHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblHeThong");
                });

            modelBuilder.Entity("CSDLGia_ASP.Models.tblPhanQuyen", b =>
                {
                    b.Property<string>("MaChucNang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DM_DanhSach")
                        .HasColumnType("int");

                    b.Property<int?>("DM_ThayDoi")
                        .HasColumnType("int");

                    b.Property<int?>("HS_DanhSach")
                        .HasColumnType("int");

                    b.Property<int?>("HS_HoanThanh")
                        .HasColumnType("int");

                    b.Property<int?>("HS_ThayDoi")
                        .HasColumnType("int");

                    b.Property<int?>("K_BaoCao")
                        .HasColumnType("int");

                    b.Property<int?>("K_ThongTin")
                        .HasColumnType("int");

                    b.Property<bool?>("PhanQuyen")
                        .HasColumnType("bit");

                    b.HasKey("MaChucNang", "TenDangNhap");

                    b.ToTable("tblPhanQuyen");
                });

            modelBuilder.Entity("CSDLGia_ASP.Models.viewDonVi_TaiKhoan", b =>
                {
                    b.Property<string>("CapDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucNang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVuKyThay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVuQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailQuanTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDiaBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhomTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQHNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NhapLieu")
                        .HasColumnType("bit");

                    b.Property<bool?>("QuanTri")
                        .HasColumnType("bit");

                    b.Property<int?>("STT")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoNgayLamViec")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDiaBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViChuQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonViHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TongHop")
                        .HasColumnType("bit");

                    b.ToView("viewDonVi_TaiKhoan");
                });
#pragma warning restore 612, 618
        }
    }
}
